### ISSUE TITLE
Snake River web map not capturing all AUs and includes AU outside assessment area

### ISSUE THREAD

**Issue by DEQrmichie** [donco/odeqstatusandtrends#28]
The parameter map for the Snake River does not show all the waterbody and reach AU segments for the Snake River. For example Oxbow Reservoir and Brownlee Reservoir are missing. It also includes watershed units and reach segments for areas that are not supposed to be included.  I think this happens for two reasons 1) AUs are being selected based on HUC12, and 2) Waterbody AUs are not included in the map. 

Like #27, I suggest we filter based on the AU IDs for the Snake River. In the bigger picture consider attributing the AU features according to the webmap units. As an interim step I pulled out all the Snake River AU waterbodies, reach segments, and watershed units and saved the features in the GIS folder under Assessment_Units.gdb.

**Comment by DEQcdonald** [comment]
Are you referring to the reservoirs being missing when it comes to the assessment unit line and polygon layers? They are included in the assessment area shapefile, but do not show up in the assessment unit parameter summary layer because there are no stations with data.

When you say that watershed units and reach segments are being included for areas outside of the assessment unit, are you referring to the water quality limited layer?

**Comment by DEQrmichie** [comment]
Sorry for not being clear. I was referencing the water quality limited layer.

**Comment by DEQcdonald** [comment]
Addressed in commit: 630f3c0bcd7801b826ab7dc982ae5055ef76005c

**Comment by DEQrmichie** [comment]
This issue still persists in the static maps that are in the word report.

**Comment by DEQcdonald** [comment]
This issue has been confirmed as fixed in the 2020 report.
